### ISSUE TITLE
Add a new dashboard item for every league year that summarizes site changes

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#164]
Example for returning players for summer 2023:

- New functionality (bid guarding, team fines, etc.)
- Rule changes
- Fall draft is hosted on the site and an interactive session.
- Integration with Yahoo
- Additional player YoY metadata.

These should be summarized and non-technical - focus should be on how these features enhance the _user's_ experience in the League.

**Comment by morkusporkus** [comment]
I agree 100%

**Comment by morkusporkus** [comment]
Ill take a look through our changes and summarize

**Comment by Lyddon7522** [comment]
Is this going to be static content on the page that gets updated with all changes or is it going to be a one time dump at the beginning of the season. I only ask because you actually push a lot of new features pretty frequently, didn't know if a link to something like the release notes would be useful or not.

**Comment by benjaminsampica** [comment]
I like that idea @Lyddon7522. I think I can hook into GitHubs API and pull a list of release notes. Would it be valuable to have a list or just the latest?

**Comment by benjaminsampica** [comment]
Reference - https://docs.github.com/en/rest/releases/releases#list-releases
