### ISSUE TITLE
[Suggestion] Adding a wiki for running the application locally

### ISSUE THREAD

**Issue by HenryMigo** [benjaminsampica/DynamoLeagueBlazor#179]
There seems to be limited documentation on how to run the solution locally other than some prerequisites, this makes it a bit difficult for those wanting to help contribute to the project. 

I have forked and tried to run using multi-project the Client and Server but get an error on the dashboard, and an error in the console with:

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: Could not load settings from '_configuration/DynamoLeagueBlazor.Client'
Error: Could not load settings from '_configuration/DynamoLeagueBlazor.Client'
```

I would be happy to write up the wiki for this but I do not have the knowledge on getting this running.

Sorry if this is stepping on toes, or comes across in a bad way, its not intended to be like that. If you do not see this being needed it can be closed.

**Comment by benjaminsampica** [comment]
Welcome back and thanks for contributing again! 

One housekeeping thing to make sure everything is setup correctly-

1. You’re running the Server project, not the Client one. Since this is WASM hosted, the client cannot really run stand-alone.

I think a wiki is a great idea if it takes a little more than this to get it going.

**Comment by HenryMigo** [comment]
No worries, so I start the server, then the docker image is running, it took a while but then it loaded the tab. I think this will need to be documented as there is nothing to suggest it's doing anything between the docker running and it creating the new tab. I assume it's doing some setup but it does seem to take awhile for first time. I will see if I can add something now I have it running.

**Comment by benjaminsampica** [comment]
I’m taking a few things away from this:

- The sql server image is large so the first-time boot is really slow locally. This needs to surface somehow to make it more obvious docker is doing its thing without it being tribal knowledge.
- Fail faster and with greater detail before it hits the configuration issue, since that’s just a red herring. I’ve had to walk a few contributors through this and it’s just not a good experience for people trying to help.
- Some sort of wiki/FAQ to walk through first time setup.

I’m going to break this out into a few issues and will close this issue at that time.
